// ============================================================
// 從 production 匯出資料庫「結構」（不含資料）→ supabase/baseline_from_prod.sql
// 用法（PowerShell）：
//   $env:SOURCE_DB_URL = "<production 連線字串>"
//   node scripts/db/dump-schema.mjs
// 連線字串在 Supabase Dashboard → Connect → Session pooler URI
// ============================================================
import pg from 'pg';
import { writeFileSync } from 'fs';

const url = process.env.SOURCE_DB_URL;
if (!url) { console.error('❌ 請先設定 SOURCE_DB_URL 環境變數'); process.exit(1); }

const client = new pg.Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
await client.connect();
console.log('✅ 已連線來源資料庫');

const out = [];
out.push('-- baseline_from_prod.sql — 由 dump-schema.mjs 產生於 ' + new Date().toISOString());
out.push('-- 只含 public schema 的「結構」，不含任何資料。');
out.push('');

// 1. Extensions
const ext = await client.query(
  `SELECT extname FROM pg_extension WHERE extname NOT IN ('plpgsql')`);
for (const r of ext.rows) out.push(`CREATE EXTENSION IF NOT EXISTS "${r.extname}";`);
out.push('');

// 2. Tables（columns + defaults + not null）
const tables = (await client.query(`
  SELECT c.relname AS tbl
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r'
  ORDER BY c.relname`)).rows.map(r => r.tbl);

const constraintNames = new Set();

for (const t of tables) {
  const cols = (await client.query(`
    SELECT a.attname AS name,
           format_type(a.atttypid, a.atttypmod) AS type,
           a.attnotnull AS notnull,
           pg_get_expr(d.adbin, d.adrelid) AS def,
           a.attidentity AS ident
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = ('public.' || quote_ident($1))::regclass
      AND a.attnum > 0 AND NOT a.attisdropped
    ORDER BY a.attnum`, [t])).rows;
  const lines = cols.map(c => {
    let l = `  "${c.name}" ${c.type}`;
    if (c.ident === 'a') l += ' GENERATED ALWAYS AS IDENTITY';
    if (c.ident === 'd') l += ' GENERATED BY DEFAULT AS IDENTITY';
    if (c.def && !c.ident) l += ` DEFAULT ${c.def}`;
    if (c.notnull) l += ' NOT NULL';
    return l;
  });
  out.push(`CREATE TABLE IF NOT EXISTS public."${t}" (\n${lines.join(',\n')}\n);`);

  // PK / UNIQUE / CHECK（先加；FK 最後統一加，避免順序問題）
  const cons = (await client.query(`
    SELECT conname, contype, pg_get_constraintdef(oid) AS def
    FROM pg_constraint
    WHERE conrelid = ('public.' || quote_ident($1))::regclass AND contype IN ('p','u','c')
    ORDER BY contype`, [t])).rows;
  for (const c of cons) {
    constraintNames.add(c.conname);
    out.push(`ALTER TABLE public."${t}" ADD CONSTRAINT "${c.conname}" ${c.def};`);
  }
  out.push('');
}

// 3. Foreign keys（所有表建完後）
out.push('-- Foreign keys');
for (const t of tables) {
  const fks = (await client.query(`
    SELECT conname, pg_get_constraintdef(oid) AS def
    FROM pg_constraint
    WHERE conrelid = ('public.' || quote_ident($1))::regclass AND contype = 'f'`, [t])).rows;
  for (const c of fks) {
    constraintNames.add(c.conname);
    out.push(`ALTER TABLE public."${t}" ADD CONSTRAINT "${c.conname}" ${c.def};`);
  }
}
out.push('');

// 4. 其他 index（非 constraint 附帶的）
out.push('-- Indexes');
const idx = (await client.query(`
  SELECT indexname, indexdef FROM pg_indexes
  WHERE schemaname = 'public'`)).rows;
for (const i of idx) {
  if (constraintNames.has(i.indexname)) continue;
  out.push(i.indexdef.replace('CREATE INDEX', 'CREATE INDEX IF NOT EXISTS')
                     .replace('CREATE UNIQUE INDEX', 'CREATE UNIQUE INDEX IF NOT EXISTS') + ';');
}
out.push('');

// 5. Views
const views = (await client.query(`
  SELECT viewname, definition FROM pg_views WHERE schemaname = 'public'`)).rows;
for (const v of views) out.push(`CREATE OR REPLACE VIEW public."${v.viewname}" AS\n${v.definition}`);
out.push('');

// 6. Functions（public schema 自訂函式）
const funcs = (await client.query(`
  SELECT pg_get_functiondef(p.oid) AS def
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.prokind = 'f'`)).rows;
for (const f of funcs) out.push(f.def + ';\n');

// 7. Triggers
const trigs = (await client.query(`
  SELECT pg_get_triggerdef(t.oid) AS def
  FROM pg_trigger t
  JOIN pg_class c ON c.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND NOT t.tgisinternal`)).rows;
for (const tg of trigs) out.push(tg.def + ';');
out.push('');

// 8. RLS 啟用狀態 + 現有 policies（照實搬——010 之後會全部重建，先如實重現現況）
out.push('-- RLS flags & existing policies');
const rls = (await client.query(`
  SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity`)).rows;
for (const r of rls) out.push(`ALTER TABLE public."${r.relname}" ENABLE ROW LEVEL SECURITY;`);

const pols = (await client.query(`
  SELECT * FROM pg_policies WHERE schemaname = 'public'`)).rows;
for (const p of pols) {
  let s = `CREATE POLICY "${p.policyname}" ON public."${p.tablename}"`;
  if (p.permissive === 'RESTRICTIVE') s += ' AS RESTRICTIVE';
  s += ` FOR ${p.cmd}`;
  if (p.roles && p.roles.length && p.roles[0] !== 'public') s += ` TO ${p.roles.join(', ')}`;
  if (p.qual) s += ` USING (${p.qual})`;
  if (p.with_check) s += ` WITH CHECK (${p.with_check})`;
  out.push(s + ';');
}

writeFileSync('supabase/baseline_from_prod.sql', out.join('\n'), 'utf-8');
console.log(`✅ 已輸出 supabase/baseline_from_prod.sql（${tables.length} 張表、${funcs.length} 個函式、${pols.length} 條 policy）`);
console.log('表清單：' + tables.join(', '));
await client.end();
